name: image deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: azure/docker-login@v1
        with:
          login-server: rg.fr-par.scw.cloud/fuelforcheap
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: martinbeentjes/npm-get-version-action@v1.0.0
        id: version
        name: get current package version

      - run: echo ::set-env name=VERSION::$CURRENT_VERSION
        env:
          CURRENT_VERSION: ${{ steps.version.outputs.current-version }}

      - run: npm install

      - name: build svelte
        run: npm run build

      - name: build the image
        run: docker build . -t rg.fr-par.scw.cloud/fuelforcheap/app:$VERSION

      - name: tag as latest
        run: docker tag rg.fr-par.scw.cloud/fuelforcheap/app:$VERSION rg.fr-par.scw.cloud/fuelforcheap/app:latest

      - name: push the image
        run: docker push rg.fr-par.scw.cloud/fuelforcheap/app:latest

      - run: docker push rg.fr-par.scw.cloud/fuelforcheap/app:$VERSION
